### ISSUE TITLE
Dashboard access

### ISSUE THREAD

**Issue by lincolnaleixo** [geeklingo/Guppy-Dashboard#1]
thanks for doing this integration but it seems something needs to be fixed, running for the first time I get this:
Error: INSERT INTO portfolio_history(checked, value, freeBTC, usedBTC, ethValue, exchange) VALUES(now(), '0.21113662','0.00000000','0.21113662','INF','Binance')
Incorrect decimal value: 'INF' for column 'ethValue' at row 1

**Comment by linkinkin** [comment]
I was able to get it done, but we need your composer autoload.php otherwise we don't know what dependencies you need

**Comment by geeklingo** [comment]
Aaaaah ok, seems like it was not able to get the ETH/BTC value for some reason. You are using with Binance right?

Seems to be because your BTC balance is showing as 0.

**Comment by geeklingo** [comment]
I'm working on an update that removes the need for the api, will be out this week

**Comment by geeklingo** [comment]
Please download the latest files.
